name: Profile with coz

on:
  push:
    branches: [ "methylation-paired-end" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Install Dependencies
      # run: |
      #   sudo apt-get update
      #   sudo apt-get install libdwarf-dev build-essential cmake docutils-common git python3 pkg-config libbz2-dev libsqlite3-dev
    - name: Install Coz
      run: |
        # From source: 
        sudo apt-get update
        sudo apt-get install libdwarf-dev
        sudo apt-get install build-essential cmake docutils-common git python3 pkg-config
        git clone https://github.com/antoyo/libelfin && cd libelfin && make && sudo make install && cd ..
        git clone https://github.com/plasma-umass/coz && cd coz && cmake . && make && sudo make install && cd ..
        sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'
      # Install normal
      # sudo apt install coz-profiler
      # Found on: https://github.com/plasma-umass/coz/issues/107#issuecomment-1063169616
      # git clone https://github.com/antoyo/libelfin.git && cd libelfin && make && sudo make install && cd ..
    - name: Check Installation
      run: |
        coz run --help
    - name: Build varlo
      run: |
        # export RUSTFLAGS="-C link-arg=-gdwarf-3"
        # cargo build --release
        ls /usr/lib/libdwarf++.so.0
        sudo ldconfig
        echo $LD_LIBRARY_PATH
        export LD_LIBRARY_PATH=/pfad/zur/libelfin:$LD_LIBRARY_PATH

    # - name: Run Varlo
    #   run : |
    #     pwd
    #     ls -R tests/resources/coz_profiling
    #     cargo run --release -- preprocess variants tests/resources/coz_profiling/ref.fa --candidates tests/resources/coz_profiling/candidates.vcf --bam tests/resources/coz_profiling/normal.bam --read-type Nanopore
    - name: Run Coz
      run: coz run --- cargo run --release -- preprocess variants tests/resources/coz_profiling/ref.fa --candidates tests/resources/coz_profiling/candidates.vcf --bam tests/resources/coz_profiling/normal.bam --read-type Nanopore
    
    
    
    # - name: Prepare Coz
    #   run: |
    #     sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'
    #     cd coz/benchmarks && cmake . && make && cd ../..
    #     coz run --- ./coz/benchmarks/toy/toy
        
    # - name: Build with debug information
    #   run: cargo build --verbose
    # - name: Varlociraptor help
    #   run: cargo run --release -- --help
