name: Profile with coz

on:
  push:
    branches: [ "methylation-paired-end" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Coz
      run: |
        sudo apt-get update
        sudo apt-get install libdwarf-dev
        sudo apt-get install build-essential cmake docutils-common git python3 pkg-config
        git clone https://github.com/antoyo/libelfin && cd libelfin && make && sudo make install && cd ..
        git clone https://github.com/plasma-umass/coz && cd coz && cmake . && make && sudo make install && cd ..
    - name: Build with debug information
      run: cargo build --verbose
    - name: Varlociraptor help
      run: cargo run --release -- --help
    - name: Run Coz
      run: coz run --release -- 
